baseURL = 'https://gaozubing.cn/'
languageCode = 'zh-cn'
theme = 'gallery'
title = '高祖兵山水画廊'
[params]
	defaultTheme = 'default'
	customCSS = ["css/custom.css"]

[params.social]
  douyin = "https://www.douyin.com/user/48740764510"
